// Copyright 2021 Manna Harbour
// https://github.com/manna-harbour/miryoku

#define MIRYOKU_LAYER_MOUSE MIRYOKU_ALTERNATIVES_NUM_FLIP
#define MIRYOKU_LAYER_NUM MIRYOKU_ALTERNATIVES_MOUSE_FLIP
#define MIRYOKU_LAYER_MEDIA MIRYOKU_ALTERNATIVES_FUN_FLIP
#define MIRYOKU_LAYER_FUN MIRYOKU_ALTERNATIVES_MEDIA_FLIP
